# options for analysis running
run:
  # default concurrency is a available CPU number
  concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - typecheck
    - dupl
    - goprintffuncname
    - govet
    - nolintlint
    - rowserrcheck
    - gofmt
    - revive
    - goimports
    - misspell
    - bodyclose
    - unconvert
    - ineffassign
    - staticcheck
    - exportloopref
    - structcheck
    - deadcode
    - depguard
    - dogsled
    - errcheck
    #- funlen
    - goconst
    - gocritic
    - gocyclo
    - gosimple
    - stylecheck
    - unused
    - varcheck
    - unparam
    - unconvert
    - whitespace

issues:
  include:
  - EXC0002 # disable excluding of issues about comments from golint
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - dupl
    # Exclude because: "string `Deployment` has 3 occurrences, but such constant `Deployment` already exists"
    # but we don't need to make them constants
    - path: controllers/transform/transform.go
      linters:
        - goconst
    # Exclude because: "string `Deployment` has 3 occurrences, but such constant `Deployment` already exists"
    # but we don't need to make them constants
    - path: controllers/kedacontroller_controller.go
      linters:
        - goconst
    # Exclude for controllers, reason:
    # "controllers/configmap_controller.go:49: 49-80 lines are duplicate of `controllers/secret_controller.go:49-80`"
    - path: _controller.go
      linters:
        - dupl
    # Exclude because: "controllers/suite_test.go:157:63: `getObject` - `namespace` always receives `namespace` (`"keda"`)"
    - path: controllers/suite_test.go
      linters:
        - unparam
    # Exclude because: "declaration has 3 blank identifiers" -> it's ok, we don't need them
    - path: resources/resources_handler.go
      linters:
        - dogsled
    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    - linters:
       - stylecheck
      text: "ST1000:"

linters-settings:
  funlen:
    lines: 80
    statements: 40
