---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: keda-operator
    app.kubernetes.io/component: keda-operator
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/part-of: keda
  name: kedaorg-certs
  namespace: keda
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-operator
  namespace: keda
  labels:
    app.kubernetes.io/name: keda-operator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keda-operator
  endpoints:
    - port: metrics
      interval: 60s
  namespaceSelector:
    any: false
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: keda-metrics-apiserver
  namespace: keda
  labels:
    app.kubernetes.io/name: keda-metrics-apiserver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keda-metrics-apiserver
  endpoints:
    - port: metrics
      interval: 60s
  namespaceSelector:
    any: false
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: keda-admission-webhooks
  name: keda-admission-webhooks
  namespace: keda
spec:
  endpoints:
  - interval: 60s
    port: metrics
  namespaceSelector:
    any: false
  selector:
    matchLabels:
      app.kubernetes.io/component: admission-webhooks
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keda-olm-operator
  namespace: keda
  labels:
    name: keda-olm-operator
spec:
  selector:
    matchLabels:
      name: keda-olm-operator
  podMetricsEndpoints:
    - targetPort: 8080
      path: /metrics
      interval: 60s
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
  name: keda-default-deny
spec:
  podSelector:
    matchExpressions:
    - {key: app, operator: In, values: [keda-operator, keda-admission-webhooks, keda-metrics-apiserver]}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
  name: keda-allow-egress-to-api-server
spec:
  egress:
  - ports:
    - port: 6443
      protocol: TCP
  podSelector:
    matchExpressions:
    - {key: app, operator: In, values: [keda-operator, keda-admission-webhooks, keda-metrics-apiserver]}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
  name: keda-allow-egress-to-dns
spec:
  egress:
  - ports:
    - port: 5353
      protocol: TCP
    - port: 5353
      protocol: UDP
  podSelector:
    matchExpressions:
    - {key: app, operator: In, values: [keda-operator, keda-admission-webhooks, keda-metrics-apiserver]}
  policyTypes:
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: keda
  labels:
    app.kubernetes.io/name: keda-admission-webhooks
  name: keda-allow-ingress-to-webhook
spec:
  ingress:
  - ports:
    - port: 9443
      protocol: TCP
  podSelector:
    matchLabels:
      app: keda-admission-webhooks
      name: keda-admission-webhooks
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
  name: keda-allow-ingress-to-metrics-api
spec:
  ingress:
  - ports:
    - port: 6443
      protocol: TCP
  podSelector:
    matchExpressions:
    - {key: app, operator: In, values: [keda-metrics-apiserver]}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
  name: keda-allow-grpc-access
spec:
  egress:
  - ports:
    - port: 9666
      protocol: TCP
    to:
    - podSelector:
        matchLabels:
          app: keda-operator
  ingress:
  - ports:
    - port: 9666
      protocol: TCP
    from:
    - podSelector:
        matchLabels:
          app: keda-metrics-apiserver
  podSelector:
    matchExpressions:
    - {key: app, operator: In, values: [keda-operator, keda-metrics-apiserver]}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
  name: keda-allow-ingress-to-metrics
spec:
  ingress:
  - ports:
    - port: 8443
      protocol: TCP
    - port: 8080
      protocol: TCP
  podSelector:
    matchExpressions:
    - {key: app, operator: In, values: [keda-operator, keda-admission-webhooks, keda-metrics-apiserver]}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: keda
  labels:
    app.kubernetes.io/name: keda
  name: keda-allow-egress-to-all
spec:
  egress:
  - ports:
    - port: 1
      endPort: 65535
      protocol: TCP
    - port: 1
      endPort: 65535
      protocol: UDP
  podSelector:
    matchExpressions:
    - {key: app, operator: In, values: [keda-operator, keda-metrics-apiserver]}
  policyTypes:
  - Egress
