apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-operator
  namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-operator
  namespace: keda
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-operator
rules:
  - apiGroups:
      - http.keda.sh
    resources:
      - httpscaledobjects
      - interceptorroutes
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - http.keda.sh
    resources:
      - httpscaledobjects/finalizers
      - interceptorroutes/finalizers
    verbs:
      - update
  - apiGroups:
      - http.keda.sh
    resources:
      - httpscaledobjects/status
      - interceptorroutes/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - keda.sh
    resources:
      - scaledobjects
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-operator
  namespace: keda
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keda-add-ons-http-operator
subjects:
  - kind: ServiceAccount
    name: keda-add-ons-http-operator
    namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-add-ons-http-operator
subjects:
  - kind: ServiceAccount
    name: keda-add-ons-http-operator
    namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-operator-auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: keda-add-ons-http-operator
    namespace: keda
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-operator-metrics
  namespace: keda
spec:
  ports:
    - name: metrics-http
      port: 8080
      protocol: TCP
      targetPort: metrics-http
    - name: metrics-https
      port: 8443
      protocol: TCP
      targetPort: metrics-https
  selector:
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/component: operator
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-operator
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: http-add-on
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-add-on
        app.kubernetes.io/component: operator
    spec:
      containers:
        - args:
            - --leader-elect
            - --zap-log-level=info
            - --zap-encoder=console
            - --zap-time-encoding=rfc3339
          env:
            - name: KEDA_HTTP_OPERATOR_EXTERNAL_SCALER_SERVICE
              value: keda-add-ons-http-external-scaler
            - name: KEDA_HTTP_OPERATOR_EXTERNAL_SCALER_PORT
              value: "9090"
            - name: KEDA_HTTP_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: ghcr.io/kedacore/http-add-on-operator:0.15.0@sha256:d579b952ff0a0c3046a49d0e066bc06d33d1944b5f89b5fac5145d89f9f78959
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
          name: operator
          ports:
            - containerPort: 8080
              name: metrics-http
            - containerPort: 8443
              name: metrics-https
            - containerPort: 8081
              name: probes
          readinessProbe:
            httpGet:
              path: /readyz
              port: probes
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: keda-add-ons-http-operator
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-interceptor
  namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-interceptor
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - http.keda.sh
    resources:
      - httpscaledobjects
      - interceptorroutes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-interceptor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-add-ons-http-interceptor
subjects:
  - kind: ServiceAccount
    name: keda-add-ons-http-interceptor
    namespace: keda
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-interceptor-admin
  namespace: keda
spec:
  ports:
    - name: admin
      port: 9090
      protocol: TCP
      targetPort: admin
  selector:
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/component: interceptor
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-interceptor-metrics
  namespace: keda
spec:
  ports:
    - name: metrics
      port: 2223
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/component: interceptor
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-interceptor-proxy
  namespace: keda
spec:
  ports:
    - name: proxy
      port: 8080
      protocol: TCP
      targetPort: proxy
    - name: proxy-tls
      port: 8443
      protocol: TCP
      targetPort: proxy-tls
  selector:
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/component: interceptor
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-interceptor
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: http-add-on
      app.kubernetes.io/component: interceptor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-add-on
        app.kubernetes.io/component: interceptor
    spec:
      containers:
        - args:
            - --zap-log-level=info
            - --zap-encoder=console
            - --zap-time-encoding=rfc3339
          env:
            - name: KEDA_HTTP_PROXY_PORT
              value: "8080"
            - name: KEDA_HTTP_ADMIN_PORT
              value: "9090"
          image: ghcr.io/kedacore/http-add-on-interceptor:0.15.0@sha256:4e88e7808652e7c438f66d67bc8a53ce6261b6081c81475bd4758602460af499
          livenessProbe:
            httpGet:
              path: /livez
              port: admin
          name: interceptor
          ports:
            - containerPort: 9090
              name: admin
            - containerPort: 8080
              name: proxy
            - containerPort: 8443
              name: proxy-tls
            - containerPort: 2223
              name: metrics
          readinessProbe:
            httpGet:
              path: /readyz
              port: admin
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: keda-add-ons-http-interceptor
      terminationGracePeriodSeconds: 45
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app.kubernetes.io/component: interceptor
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-interceptor
  namespace: keda
spec:
  maxReplicaCount: 50
  minReplicaCount: 1
  pollingInterval: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keda-add-ons-http-interceptor
  triggers:
    - metadata:
        interceptorTargetPendingRequests: "200"
        scalerAddress: keda-add-ons-http-external-scaler:9090
      type: external
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: scaler
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-scaler
  namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: scaler
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-scaler
rules:
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - http.keda.sh
    resources:
      - httpscaledobjects
      - interceptorroutes
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: scaler
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-scaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-add-ons-http-scaler
subjects:
  - kind: ServiceAccount
    name: keda-add-ons-http-scaler
    namespace: keda
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: scaler
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-external-scaler
  namespace: keda
spec:
  ports:
    - name: grpc
      port: 9090
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/component: external-scaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: scaler
    app.kubernetes.io/name: http-add-on
    app.kubernetes.io/part-of: keda
  name: keda-add-ons-http-scaler
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: http-add-on
      app.kubernetes.io/component: external-scaler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-add-on
        app.kubernetes.io/component: external-scaler
    spec:
      containers:
        - args:
            - --zap-log-level=info
            - --zap-encoder=console
            - --zap-time-encoding=rfc3339
          env:
            - name: KEDA_HTTP_SCALER_TARGET_ADMIN_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KEDA_HTTP_SCALER_TARGET_ADMIN_DEPLOYMENT
              value: keda-add-ons-http-interceptor
            - name: KEDA_HTTP_SCALER_TARGET_ADMIN_SERVICE
              value: keda-add-ons-http-interceptor-admin
            - name: KEDA_HTTP_SCALER_TARGET_ADMIN_PORT
              value: "9090"
            - name: KEDA_HTTP_SCALER_PORT
              value: "9090"
          image: ghcr.io/kedacore/http-add-on-scaler:0.15.0@sha256:f748178bc4af9e546d5da38c4e1b1d8d236a343bb30927b292131c6f4c978394
          livenessProbe:
            failureThreshold: 3
            grpc:
              port: 9090
              service: liveness
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: scaler
          ports:
            - containerPort: 9090
              name: grpc
            - containerPort: 2223
              name: metrics
          readinessProbe:
            failureThreshold: 3
            grpc:
              port: 9090
              service: readiness
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1000m
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: keda-add-ons-http-scaler
      terminationGracePeriodSeconds: 10
