# permissions for end users to edit kedacontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kedacontroller-editor-role
rules:
- apiGroups:
  - keda.sh
  resources:
  - kedacontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keda.sh
  resources:
  - kedacontrollers/status
  verbs:
  - get
