# permissions for end users to view kedacontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kedacontroller-viewer-role
rules:
- apiGroups:
  - keda.sh
  resources:
  - kedacontrollers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keda.sh
  resources:
  - kedacontrollers/status
  verbs:
  - get
