blank_issues_enabled: true
contact_links:
  - name: Ask a question about KEDA OLM Operator or get support
    url: https://github.com/kedacore/keda-olm-operator/discussions/new
    about: Ask a question or request support for using KEDA OLM Operator
