---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: keda-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  # - services/finalizers
  # - endpoints
  - events
  - configmaps
  - secrets
  # - namespaces
  - external
  - configmaps/status
  verbs:
  - '*'
- apiGroups:
  # - apps
  # resources:
  # - deployments
  # - deployments/finalizers
  # - replicasets
  # verbs:
  - '*'
# - apiGroups:
#   - batch
  resources:
  # - jobs
  # verbs:
  - '*'
# - apiGroups:
#   - monitoring.coreos.com
#   resources:
#   - servicemonitors
  verbs:
  - get
  # - create
- apiGroups:
  # - keda.k8s.io
  # resources:
  - '*'
  resources:
  - '*/scale'
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  # labels:
  name: keda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-operator
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: keda
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-operator
  namespace: keda
  labels:
    app: keda-operator
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: keda-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-operator
  template:
    metadata:
      labels:
        app: keda-operator
        name: keda-operator
      name: keda-operator
    spec:
      serviceAccountName: keda-operator
      containers:
        - name: keda-operator
          image: docker.io/kedacore/keda:v2
          command:
            - /keda
          args:
            - --enable-leader-election
            - --zap-log-level=info
            - --zap-encoder=console
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
      terminationGracePeriodSeconds: 10
      nodeSelector:
        beta.kubernetes.io/os: linux
