---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: keda-external-metrics-reader
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-operator
  creationTimestamp: null
  name: keda-external-metrics-reader
rules:
- apiGroups:
  - "external.metrics.k8s.io"
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-system-auth-delegator
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-operator
  name: keda:system:auth-delegator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-auth-reader
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-operator
  name: keda-auth-reader
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: keda-operator
  namespace: keda
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keda-hpa-controller-external-metrics
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-operator
  name: keda-hpa-controller-external-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-external-metrics-reader
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keda-metrics-apiserver
    app.kubernetes.io/name: keda-metrics-apiserver
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-operator
  name: keda-metrics-apiserver
  namespace: keda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-metrics-apiserver
  template:
    metadata:
      labels:
        app: keda-metrics-apiserver
      name: keda-metrics-apiserver
    spec:
      serviceAccountName: keda-operator
      containers:
        - name: keda-metrics-apiserver
          image: docker.io/kedacore/keda-metrics-adapter:v2
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
          args:
          - /usr/local/bin/keda-adapter
          - --secure-port=6443
          - --logtostderr=true
          - --v=0
          ports:
          - containerPort: 6443
            name: https
          - containerPort: 8080
            name: http
          volumeMounts:
          - mountPath: /tmp
            name: temp-vol
      nodeSelector:
        beta.kubernetes.io/os: linux
      volumes:
      - name: temp-vol
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: keda-metrics-apiserver
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-operator
  name: keda-metrics-apiserver
  namespace: keda
spec:
  ports:
  - name: https
    port: 443
    targetPort: 6443
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: keda-metrics-apiserver
---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  labels:
    app.kubernetes.io/name: v1beta1.external.metrics.k8s.io
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-operator
  name: v1beta1.external.metrics.k8s.io
spec:
  service:
    name: keda-metrics-apiserver
    namespace: keda
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100