---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: keda
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-operator
  name: keda
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: keda-operator
    app.kubernetes.io/version: latest
    app.kubernetes.io/part-of: keda-operator
  name: keda-operator
  namespace: keda
