apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.1.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: keda-olm-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: KedaController is the Schema for the kedacontrollers API
      displayName: Keda Controller
      kind: KedaController
      name: kedacontrollers.keda.sh
      version: v1alpha1
  description: test-description
  displayName: test-displayname
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - test-keyword
  links:
  - name: Keda Olm Operator
    url: https://keda-olm-operator.domain
  maturity: alpha
  provider:
    name: test-providersname
    url: test-relevanturl
  version: 0.0.0
