apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: example-scaledobject
spec:
  scaleTargetRef:
    deploymentName: example-deployment
    containerName: example-container
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 0
  maxReplicaCount: 100
  triggers:
    - type: example-trigger
      metadata:
        namespace: examle-namespace
