apiVersion: apps/v1
kind: Deployment
metadata:
  name: keda-olm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keda-olm-operator
  template:
    metadata:
      labels:
        name: keda-olm-operator
    spec:
      serviceAccountName: keda-olm-operator
      containers:
        - name: keda-olm-operator
          image: docker.io/kedacore/keda-olm-operator:master
          command:
          - keda-olm-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keda-olm-operator"
