kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: keda-olm-operator
subjects:
- kind: ServiceAccount
  name: keda-olm-operator
  namespace: keda
roleRef:
  kind: ClusterRole
  name: keda-olm-operator
  apiGroup: rbac.authorization.k8s.io
