name: Create cluster using KinD
on:
  push:
    branches:
      - master

jobs:
  kind:
    runs-on: ubuntu-latest
    container: kedacore/build-tools:v2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup kubernetes
        uses: engineerd/setup-kind@v0.3.0
      
      - name: Run e2e tests
        run: |
          kubectl create namespace keda
          make test-e2e